# Generated by Django 5.0.1 on 2024-05-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('mdp', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fourniseur',
            fields=[
                ('NIF', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fourniseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.fourniseur')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prix_achat', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('qte', models.IntegerField()),
                ('fourniseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.fourniseur')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id_achat', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField()),
                ('somme', models.FloatField()),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.livraison')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Ventecli',
            fields=[
                ('id_vente', models.AutoField(primary_key=True, serialize=False)),
                ('qte', models.IntegerField()),
                ('somme', models.FloatField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.commande')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrateur.medicament')),
            ],
        ),
    ]
